### ISSUE TITLE
VNext Configuration?

### ISSUE THREAD

**Issue by ghost** [Emzi0767/DSharpPlus-Example-Bot#2]
I've been looking at the code in example 3, and I have used the join and leave commands in my bot, just to try it out. I installed DSharpPlus.VoiceNext in Nuget, but it still says that it is not configured. I do not know much about the DSharpPlus library, but I understand some of the code. Can someone explain how to configure it?

**Comment by Emzi0767** [comment]
Follow the VNext setup instructions in the documentation.
