### ISSUE TITLE
I Have An Issue With Runing My Bot!

### ISSUE THREAD

**Issue by WeirdYoda5** [Emzi0767/DSharpPlus-Example-Bot#5]
![Problem](https://user-images.githubusercontent.com/62953418/78282843-9b6be280-7525-11ea-940b-b894087ce2d0.PNG)
![Problem2](https://user-images.githubusercontent.com/62953418/78282848-9dce3c80-7525-11ea-9509-0c21b28e2f8b.PNG)

Can Enyone Help Me?

**Comment by Emzi0767** [comment]
Outside the scope of this repository. If you need help, visit the official support server.
