### ISSUE TITLE
VoiceNextClient missing refrence

### ISSUE THREAD

**Issue by jihadkhawaja** [Emzi0767/DSharpPlus-Example-Bot#7]
Read docs and everything still getting "Not connected in this guild." what should i do, ik many others stuck on the same problem

**Comment by Kiritsu** [comment]
VoiceNext is broken in version 3.2.3 of the library. Please update to 4.0 by following the guides here: https://dsharpplus.github.io/articles/advanced/nightly_builds.html and then migrate your code to 4.0!
